name: OpenEMS Edge Server
version: "2025.6.0"
slug: openems_edge
description: "OpenEMS Edge Server – Energie‑Management"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
ports:
  8085/tcp: 8085
volumes:
  - openems_edge_config:/etc/openems.d
  - openems_edge_data:/var/lib/openems
environment: {}
image: "openems/edge:2025.6.0"
