name: OpenEMS Edge
version: "1.0.0"
slug: openems_edge
description: OpenEMS Energie-Management-Plattform
arch:
  - amd64
  - aarch64
startup: application
boot: auto
ports:
  8080/tcp: 8080
  8085/tcp: 8085
image: "openems/edge:latest"
volumes:
  - config:/var/opt/openems/config
  - data:/var/opt/openems/data
