name: OpenEMS UI Edge
version: "2025.6.0"
slug: openems_ui_edge
description: "OpenEMS Web UI für Edge Server"
arch:
  - amd64
  - aarch64
  - armv7
  - i386
startup: application
boot: auto
ports:
  8080/tcp: 80
environment:
  # WebSocket-Verbindung zum Edge-Container
  UI_WEBSOCKET: "ws://openems_edge:8085"
image: "openems/edge:latest"
