name: Tailscale2
slug: tailscale2
description: "Zero config VPN (zweite Instanz, getrennt vom Original)"
version: "dev"
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
ports:
  8090/tcp: 8090
ports_description:
  8090/tcp: "Tailscale2 Web UI"
map:
  - share:rw
  - ssl
  - config:rw
options:
  log_level: info
schema:
  log_level: list(debug|info|warning|error)
