name: Tailscale2
slug: tailscale2
description: "Zero config VPN (zweite Instanz, HA-kompatibel, vollständig)"
version: "dev"
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
map:
  - share:rw
  - config:rw
options:
  log_level: info
schema:
  log_level: list(debug|info|warning|error)
