---
name: "OpenEMS UI Edge2"
version: "2025.6.0"
slug: "openems_ui_edge"
description: "OpenEMS Web UI für Edge Server"
arch:
  - amd64
  - aarch64
  - armv7
  - i386
startup: application
boot: auto
init: false
ports:
  8080/tcp: 80
environment:
  UI_WEBSOCKET: ws://openems_edge:8085
image: "docker.io/openems/ui-edge:latest"
